### ISSUE TITLE
Ivanov 27.05.2021 INFODAY

### ISSUE THREAD

**Issue by it48dmt** [SmartSystemLtd/planningRepo#181]
- [x] Полностью разобраться в сервисдеск и получить инструктаж от Д.А.
- [ ] Сделать гайд по сервисдеск #189
- [ ] Заполнить свой пк в сервисдеск #189
- [x] Разобраться с лицензией Цхай
- [ ] Подготовиться к замене ССД в сервере #151
- [ ] ~Изучить education~
- [x] Разобраться со сканером МРС
- [x] Навигатор ПВН подсказать что с апгрейдом
- [x] Провести тест железа со старого пк
- [x] Проверить ссд на VDI сервера
