### ISSUE TITLE
02.06 InfoDay Lysenko A.V.

### ISSUE THREAD

**Issue by itinzeneer** [SmartSystemLtd/planningRepo#235]
- [x] 3286 Монитор Алены Жужжит #237 
- [x] 1962 ноутбук Иван Гармония Wi-Fi #89 
- [x] 3213 Собрать ПК и установить ОС и пакет Макс #241
- [x] 3219 В почте zakaz@it48.ru у Мирошниченко Е. не отображается письмо от 26.05.21 в 15:24, а у других сотрудников отображается #242
- [ ]
